version: '3.8'

services:
  liquibase-ui:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    volumes:
      - ./logs:/app/logs
      - ./db:/app/db
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - liquibase-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: liquibase_ui
      POSTGRES_USER: liquibase
      POSTGRES_PASSWORD: liquibase_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - liquibase-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - liquibase-ui
    restart: unless-stopped
    networks:
      - liquibase-network

volumes:
  postgres_data:

networks:
  liquibase-network:
    driver: bridge
