{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "liquibase-ui.fullname" . }}
  labels:
    {{- include "liquibase-ui.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "liquibase-ui.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: {{ .Values.config.port }}
  - from:
    - podSelector:
        matchLabels:
          {{- include "liquibase-ui.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: {{ .Values.config.port }}
  egress:
  {{- if .Values.postgresql.enabled }}
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: postgresql
    ports:
    - protocol: TCP
      port: 5432
  {{- end }}
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
    - protocol: UDP
      port: 53
{{- end }}
